site_name: Course Notes

theme: 
  name: material
  icon: 
    admonition:
      note: material/pencil
      tip: material/lightbulb-on
      warning: material/alert
      danger: material/skull


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences